### ISSUE TITLE
Дополнить свойства композиции

### ISSUE THREAD

**Issue by pevel-dev** [PavelPaha/abstracts#3]
Кажется в качестве теорем было больше свойств композиции, если нет поправь меня:

- Композиция всюду определенных (однозначных, сюръективных, инъективных) отображения является вюду определенным отображением.
- Отображение, обратное всюду определенному отображению, сюръективно; 
- Отображение, обратное однозначному отображению, инъективно;
- Отображение, обратное сюръективному отображению, всюду определенное;
- Отображение, обратное инъективному отображению, однозначно.
- Композиция взаимно однозначных отображений является взаимно однозначным отображением.
- Отображение, обратное взаимно однозначному отображению, взаимно однозначно.

**Comment by PavelPaha** [comment]
Павел, Вы правы. Добавил в конспект
