### ISSUE TITLE
Свойства не доказаны умышленно или надо доказать?

### ISSUE THREAD

**Issue by kozlov-ma** [PavelPaha/abstracts#7]
Страница 12, "Действия с векторами в координатной форме"
![image](https://user-images.githubusercontent.com/110295967/211042098-59dd22be-bbb3-4d9c-ae9e-d5e55a27d2b4.png)

Наверное стоит доказать. Более того, некоторые действия справедливы только для ортонормированного базиса.

**Comment by kozlov-ma** [comment]
Координаты середины отрезка и расстояние между точками это точно действия с **_векторами_**?

**Comment by sellerbto** [comment]
плюс точно ли нужны все эти действия? во всех учебниках упоминается только сложение и умножение на скаляр

**Comment by PavelPaha** [comment]
Вы правы
